config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/thank-you', to: 'static_pages#thanks'

  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :articles
  resources :account_activations, only: [:edit]
  resources :subscribes, only: [:new, :create]
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :title, :text, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_as_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
  	@article = Article.new
    if !logged_in?
      redirect_to login_path, flash: { error: 'Please log in to create new article.'}
    else
      render 'new'
    end
  end

  def edit
  end

  def create
  	@article = Article.new(allowed_params)

  	if @article.save
		  redirect_to root_path, flash: { notice: 'Article was successfully created.' }
  	else
  		render 'new'
  	end
  end

  def update
  	if @article.update_attributes(allowed_params)
      redirect_to root_path, flash: { notice: 'Article was successfully updated.' }
    else
      render 'edit'
    end
  end

  def destroy
  	@article.destroy
  	redirect_to root_path, flash: { notice: 'Article was successfully deleted.' }
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  # Confirms a logged-in user.
  def logged_in_as_user
    unless logged_in?
      redirect_to login_path, flash: { error: 'Please log in to edit the article.'}
    end
  end

  # Confirms the correct user article.
  def correct_user
    @article = Article.find(params[:id])
    redirect_to root_url, flash: { error: 'Article can be edited/viewed/deleted by their own user!!'} unless @article.user.id == current_user.id
  end

  def allowed_params
  	params.require(:article).permit(:title, :text, :user_id)
  end
end

app/views/articles/_form.html.haml
= f.text_field :title
= f.text_area :text
= f.hidden_field :user_id, value: current_user.id
= f.submit "Save Article", class: 'btn btn-success'
= link_to 'Back', root_path, class: 'btn btn-default'

app/views/articles/edit.html.haml
.form-display
  %h3.center Editing Article

  = bootstrap_form_for @article, :html => { :multipart => true } do |f|
    = render partial: 'form', locals: {f: f}

app/views/articles/index.html.haml
%h2.heading Leeds Diary...

%table.table.table-bordered.table-striped
  %colgroup
    %col.col-sm-2
    %col.col-sm-7
    %col.col-sm-3
  %tr
    %th{style: "text-align: center"} Title
    %th{style: "text-align: center"} Article Text
    %th{style: "text-align: center"} Action
  - @articles.each do |article|
    %tr
      %td{style: "text-align: center"}= article.title
      %td{style: "text-align: center"}= article.text
      %td{style: "text-align: center"}
        = link_to 'Show', article, class: 'btn btn-warning'
        = link_to 'Edit', edit_article_path(article), class: 'btn btn-primary'
        = link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'
    - if @articles.size == 0
      %tr
        %td.center{colspan: "5"} Sorry: There are currently no users to display.

app/views/articles/new.html.haml
.form-display
  %h2.center New Article

  = bootstrap_form_for @article, url: articles_path do |f|
    = render partial: 'form', locals: {f: f}

app/views/articles/show.html.haml
.article
  .article-heading
    .heading-text
      %h2= @article.title
      %p Posted on : #{@article.created_at.strftime('%v')} | Created #{time_ago_in_words(@article.created_at)} ago
  .article-body
    %p= @article.text