config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/thank-you', to: 'static_pages#thanks'

  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :articles
  resources :account_activations, only: [:edit]
  resources :subscribes, only: [:new, :create]
end

app/views/shared/_flash.html.haml
- [:notice, :error, :message].each do |name|
  - if flash[name]
    .col-xs-12
      - case name
      - when :notice
        .alert.alert-success
          %button.close{"data-dismiss" => "alert"} ×
          %strong Success!
          = flash[name].html_safe
      - when :error
        .alert.alert-danger
          %button.close{"data-dismiss" => "alert"} ×
          %strong Error!
          = flash[name].html_safe
      - when :message
        .alert.alert-info
          %button.close{"data-dismiss" => "alert"} ×
          %strong Info!
          = flash[name].html_safe

app/views/shared/_header.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .navbar-header
    %button.navbar-toggle{data: { target: "#navbarCollapse", toggle: "collapse"}}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to 'Sample App', root_path, class: "navbar-brand"
  #navbarCollapse.collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right
      //%li= link_to 'Contact', about_path, class: 'btn btn-default'
      - if logged_in?
        %li= link_to 'Users', users_path, class: 'btn btn-success'
        %li= link_to 'Create Article', new_article_path, class: 'btn btn-default'
        %li.dropdown
          //= link_to 'Account', class: 'btn btn-default dropdown-toggle', data: { toggle: 'dropdown' }
          %a{href: "#", class: "btn btn-default dropdown-toggle", role: "button", data:{ toggle: "dropdown" }}
            Dropdown
            %span.caret
          %ul.dropdown-menu
            %li= link_to 'Profile', current_user
            %li= link_to 'Settings', edit_user_path(current_user)
            %li= link_to 'Logout', logout_path, method: 'delete'
        %li= link_to 'Help', help_path, class: 'btn btn-default'
      - else
        %li= link_to 'Login', login_path, class: 'btn btn-default'
        %li= link_to 'Subscribe', new_subscribe_path, class: 'btn btn-success'